# 是否开放注册
enableSignUp: true

#公告
announcement:
  autoShow: false     #进入首页后自动展示
  content: 暂无公告    #公告内容

#设备
repository:
  - ItemID: 1         #设备编号，从1开始的整数
    Item: item1       #设备名称
    ItemAdress: Lab   #设备地址(未启用)
  - ItemID: 2
    Item: item2
    ItemAdress: Lab
  - ItemID: 3
    Item: item3
    ItemAdress: Lab
  - ItemID: 4
    Item: item4
    ItemAdress: Lab
  - ItemID: 5
    Item: item5
    ItemAdress: Lab
  - ItemID: 6
    Item: item6
    ItemAdress: Lab
  - ItemID: 7
    Item: item7
    ItemAdress: Lab
  - ItemID: 8
    Item: item8
    ItemAdress: Lab
  - ItemID: 9
    Item: item9
    ItemAdress: Lab