# 是否开放注册
enableSignUp: true

# 历史记录排列顺序 
historyOrder: asc        # asc升序 desc降序

#公告
announcement:
  autoShow: false      #进入首页后自动展示
  content: 暂无公告     #公告内容

#设备
repository:
  - tab: tab1                  #组名
    showTimeInfo: true         #是否显示时间信息
    header:                    
      - 材料
      - 温度
    list:
      - ItemID: 1             #设备编号，从1开始的整数
        Item: 设备1           #设备名称
        Description: 描述1    #设备说明(可选项，非必须)
      - ItemID: 2
        Item: 设备2
        Description: 描述2
      - ItemID: 3
        Item: 设备3
        Description: 描述3
      - ItemID: 4
        Item: 设备4
      - ItemID: 5
        Item: 设备5
    
  - tab: tab2
    showTimeInfo: false
    header: 
      - 气氛
    list:
      - ItemID: 6
        Item: 设备6
        Description: 描述6
      - ItemID: 7
        Item: 设备7
        Description: 描述7
      - ItemID: 8
        Item: 设备8
      - ItemID: 9
        Item: 设备9
      - ItemID: 10
        Item: 设备10
        Description: 描述10

  - tab: tab3
    showTimeInfo: false
    header: 
    list:
      - ItemID: 11             
        Item: 设备11           
        Description: 描述11    
      - ItemID: 12
        Item: 设备12
        Description: 描述12
      - ItemID: 13
        Item: 设备13
        Description: 描述13
      - ItemID: 14
        Item: 设备14
      - ItemID: 15
        Item: 设备15

  - tab: tab4
    showTimeInfo: true
    header: 
    list:
      - ItemID: 16
        Item: 设备16
        Description: 描述16
      - ItemID: 17
        Item: 设备17
        Description: 描述17
      - ItemID: 18
        Item: 设备18
      - ItemID: 19
        Item: 设备19
      - ItemID: 20
        Item: 设备20
        Description: 描述20
